allow_all_imports: true
hass_is_global: false
apps:
  solis_flux_times:
    forecast_remaining: 'energy_production_today_remaining' # entity id of solar forecast remaining energy (kWh) today - in 'sensor' domain
    morning_requirement: 12.0 # target kWh level for rest of the day (solar predicted + battery stored) at morning charge period
    evening_requirement: 5.0 # target kWh level for rest of the day (solar predicted + battery stored) at evening discharge period
    cron_before: 20 # minutes (default 20) before start of periods below to set charging/discharging times based on target levels
    solis_control:
      key_secret: !secret solis_key_secret
      key_id: !secret solis_key_id
      user_name: !secret solis_user_name
      password: !secret solis_password
      station_id: !secret solis_station_id
      #api_url: = 'https://www.soliscloud.com:13333' # default
      battery_capacity: 7.1 # in kWh - nominal stored energy of battery at 100% SOC (eg 2 * Pylontech US3000C with Nominal Capacity of 3.55 kWh each)
      battery_max_current: 74 # in amps (eg 2 * Pylontech US3000C with Recommend Charge Current of 37A each)
      # Also see https://www.youtube.com/watch?v=h1A80cSOrhA to view battery Dis/Charging Current Limits
      inverter_max_current: 62.5 # in amps - see inverter datasheet specs for 'Max. charge / discharge current'  (eg 62.5A or 100A)
      charge_period: # Octopus Flux Cheap period in morning when energy can be imported from the grid at low rates
        start: "02:05" # HH:MM string
        end: "04:55" # HH:MM string
        current: 50 # in amps
      discharge_period: # Octopus Flux Peak period in evening when energy can be exported to the grid at high rates
        start: "16:05" # HH:MM string
        end: "18:55" # HH:MM string
        current: 50 # in amps